### PR TITLE
closes #52: Scale down sidebar and fix jumping when using collapse button

### LINKED ISSUE #52: Scale down sidebar
"plainly logo should be way smaller, it's out of proportion comparing to rest of the elements.. plus if smaller, maybe the side bar expanded could end up being smaller as well, seems like a lot of space waisted"

### PR DESCRIPTION
**Pull request by vladavoX**

### CODE REVIEW

File: plainly-plugin/src/ui/components/navigation/Sidebar.tsx [hunk 1]
```diff
@@ -30,12 +30,12 @@ export default function Sidebar() {
...
             <SidebarResources />
-            <div className="flex shrink-0 h-10 items-center justify-between">
-              {sidebarOpen && <PlainlyLogo className="h-10 w-auto" />}
+            <div className="flex shrink-0 h-8 items-center justify-between">
+              {sidebarOpen && <PlainlyLogo className="h-8 w-auto" />}
               <button
                 type="button"
                 onClick={handleSidebarOpen}
-                className="text-gray-400 hover:text-white hover:bg-[rgb(43,43,43)] cursor-pointer rounded-md px-2 py-1 flex items-center justify-center text-xs -mx-2.5"
+                className="text-gray-400 hover:text-white hover:bg-[rgb(43,43,43)] cursor-pointer rounded-md px-2 py-1 flex items-center justify-center text-xs -mx-2.5 h-[25px]"
```
Comment (vladavoX) [inline plainly-plugin/src/ui/components/navigation/Sidebar.tsx:38]: there were some jumping issues when collapsing...`li` size was 27, and without 25 or something like that...

File: plainly-plugin/src/ui/components/navigation/SidebarLinks.tsx [hunk 2]
```diff
@@ -23,7 +23,7 @@ export default function SidebarLinks({
       <li>
         <ul className="-mx-2.5 space-y-1">
           {links.map((link) => (
-            <li key={link.name} className="w-full">
+            <li key={link.name} className="w-full h-[25px]">
```
Comment (vladavoX) [inline plainly-plugin/src/ui/components/navigation/SidebarLinks.tsx:26]: same as above

File: plainly-plugin/src/ui/components/navigation/SidebarLinks.tsx [hunk 3]
```diff
@@ -32,7 +32,7 @@ export default function SidebarLinks({
                     link.to === currentPage
                       ? 'bg-[rgb(43,43,43)] text-white'
                       : 'text-gray-400 hover:bg-[rgb(43,43,43)] hover:text-white',
-                    'group flex gap-x-2 rounded-md px-2 py-1 text-xs font-medium relative items-center w-full min-h-[25px]',
+                    'group flex gap-x-2 rounded-md px-2 py-1 text-xs font-medium relative items-center w-full h-[25px]',
```
Comment (vladavoX) [inline plainly-plugin/src/ui/components/navigation/SidebarLinks.tsx:35]: same as above

**Review by ivansenic — APPROVED** [review]
Very good solution :+1:
